"""create_all_phase1_tables

Revision ID: bfc45372c779
Revises: e0c51a917e8e
Create Date: 2026-06-25 10:36:56.848158
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bfc45372c779'
down_revision: Union[str, None] = 'e0c51a917e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variable_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_table', sa.String(length=255), nullable=True),
    sa.Column('lookup_keys', sa.JSON(), nullable=False),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('product_applicability', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('basis_applicability', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variable_registry_name'), 'variable_registry', ['name'], unique=True)
    op.create_table('assumption_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factor_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formula_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('output_variable', sa.String(length=255), nullable=False),
    sa.Column('function_ref', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('product_applicability', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('basis_applicability', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['output_variable'], ['variable_registry.name'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inforce_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('columns_detected', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('projection_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assumption_tables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('set_id', sa.String(length=36), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('table_type', sa.String(length=100), nullable=False),
    sa.Column('lookup_keys', sa.JSON(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['assumption_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factor_tables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('set_id', sa.String(length=36), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('table_type', sa.String(length=100), nullable=False),
    sa.Column('lookup_keys', sa.JSON(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['factor_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formula_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('formula_id', sa.String(length=36), nullable=False),
    sa.Column('depends_on_variable', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_variable'], ['variable_registry.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['formula_id'], ['formula_registry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inforce_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['inforce_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inforce_records_policy_id'), 'inforce_records', ['policy_id'], unique=False)
    op.create_table('run_outputs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=100), nullable=False),
    sa.Column('scenario_id', sa.String(length=100), nullable=False),
    sa.Column('projection_month', sa.Integer(), nullable=False),
    sa.Column('variable_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('product', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    info={'description': 'Composite index on (run_id, policy_id, scenario_id, projection_month)'}
    )
    op.create_index(op.f('ix_run_outputs_run_id'), 'run_outputs', ['run_id'], unique=False)
    op.create_table('scenario_tables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('set_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['scenario_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trace_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=100), nullable=False),
    sa.Column('scenario_id', sa.String(length=100), nullable=False),
    sa.Column('projection_month', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.String(length=36), nullable=True),
    sa.Column('variable_name', sa.String(length=255), nullable=False),
    sa.Column('input_values', sa.JSON(), nullable=True),
    sa.Column('output_value', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_table', sa.String(length=255), nullable=True),
    sa.Column('lookup_keys', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['formula_id'], ['formula_registry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    info={'description': 'Composite index on (run_id, policy_id, projection_month, variable_name)'}
    )
    op.create_index(op.f('ix_trace_logs_run_id'), 'trace_logs', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trace_logs_run_id'), table_name='trace_logs')
    op.drop_table('trace_logs')
    op.drop_table('scenario_tables')
    op.drop_index(op.f('ix_run_outputs_run_id'), table_name='run_outputs')
    op.drop_table('run_outputs')
    op.drop_index(op.f('ix_inforce_records_policy_id'), table_name='inforce_records')
    op.drop_table('inforce_records')
    op.drop_table('formula_dependencies')
    op.drop_table('factor_tables')
    op.drop_table('assumption_tables')
    op.drop_table('scenario_sets')
    op.drop_table('runs')
    op.drop_table('inforce_files')
    op.drop_table('formula_registry')
    op.drop_table('factor_sets')
    op.drop_table('assumption_sets')
    op.drop_index(op.f('ix_variable_registry_name'), table_name='variable_registry')
    op.drop_table('variable_registry')
    # ### end Alembic commands ###