"""add_composite_indexes

Revision ID: fbe10ad9a08b
Revises: bfc45372c779
Create Date: 2026-06-25 10:44:14.182975
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fbe10ad9a08b'
down_revision: Union[str, None] = 'bfc45372c779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_run_outputs_lookup', 'run_outputs', ['run_id', 'policy_id', 'scenario_id', 'projection_month'], unique=False)
    op.create_index('idx_trace_logs_lookup', 'trace_logs', ['run_id', 'policy_id', 'projection_month', 'variable_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trace_logs_lookup', table_name='trace_logs')
    op.drop_index('idx_run_outputs_lookup', table_name='run_outputs')
    # ### end Alembic commands ###